<?php

namespace ContainerCKHovzO;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9mpcfmmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9mpcfmm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9mpcfmm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'image' => ['privates', '.errored..service_locator.9mpcfmm.App\\Entity\\Image', NULL, 'Cannot autowire service ".service_locator.9mpcfmm": it references class "App\\Entity\\Image" but no such service exists.'],
        ], [
            'image' => 'App\\Entity\\Image',
        ]);
    }
}
