<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNUbYRYx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNUbYRYx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNUbYRYx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNUbYRYx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNUbYRYx\App_KernelDevDebugContainer([
    'container.build_hash' => 'NUbYRYx',
    'container.build_id' => '447220b5',
    'container.build_time' => 1716463530,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNUbYRYx');
