<?php

namespace ContainerNUbYRYx;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TBkMUiPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TBkMUiP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TBkMUiP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'imageRepository' => ['privates', 'App\\Repository\\ImageRepository', 'getImageRepositoryService', true],
        ], [
            'imageRepository' => 'App\\Repository\\ImageRepository',
        ]);
    }
}
