<?php

namespace ContainerNUbYRYx;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VYKnG7DService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VYKnG7D' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VYKnG7D'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'comment' => ['privates', '.errored..service_locator.VYKnG7D.App\\Entity\\Admin\\Comment', NULL, 'Cannot autowire service ".service_locator.VYKnG7D": it references class "App\\Entity\\Admin\\Comment" but no such service exists.'],
        ], [
            'comment' => 'App\\Entity\\Admin\\Comment',
        ]);
    }
}
