<?php

namespace ContainerNUbYRYx;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_K31Pr2sService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.K31Pr2s' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.K31Pr2s'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'message' => ['privates', '.errored..service_locator.K31Pr2s.App\\Entity\\Admin\\Messages', NULL, 'Cannot autowire service ".service_locator.K31Pr2s": it references class "App\\Entity\\Admin\\Messages" but no such service exists.'],
        ], [
            'message' => 'App\\Entity\\Admin\\Messages',
        ]);
    }
}
