<?php

namespace ContainerNUbYRYx;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PcTrxtQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pcTrxtQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pcTrxtQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ev' => ['privates', '.errored..service_locator.pcTrxtQ.App\\Entity\\Ev', NULL, 'Cannot autowire service ".service_locator.pcTrxtQ": it references class "App\\Entity\\Ev" but no such service exists.'],
        ], [
            'ev' => 'App\\Entity\\Ev',
        ]);
    }
}
