<?php

namespace ContainerNUbYRYx;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OZ7S8vjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oZ7S8vj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oZ7S8vj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'evRepository' => ['privates', 'App\\Repository\\EvRepository', 'getEvRepositoryService', true],
        ], [
            'evRepository' => 'App\\Repository\\EvRepository',
        ]);
    }
}
