<?php

namespace ContainerNUbYRYx;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.VYKnG7D.App\Entity\Admin\Comment' shared service.
     *
     * @return \App\Entity\Admin\Comment
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.VYKnG7D": it references class "App\\Entity\\Admin\\Comment" but no such service exists.');
    }
}
