<?php

namespace ContainerNUbYRYx;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessagesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.K31Pr2s.App\Entity\Admin\Messages' shared service.
     *
     * @return \App\Entity\Admin\Messages
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.K31Pr2s": it references class "App\\Entity\\Admin\\Messages" but no such service exists.');
    }
}
